#!/bin/bash
set -e
# Setting the password
sed -i -e "s/root_password_sha2 =$/root_password_sha2 = $(echo -n $GRAYLOG2_PASSWORD | sha256sum | awk '{print $1}')/" /etc/graylog2.conf
# Wait for mongodb
while ! echo exit | (curl -X GET -SsI localhost:27017 2>&1 | grep -o "200 OK"); do sleep 3; done
# Wait for elasticsearch
while ! echo exit | (curl -X GET -SsI localhost:9200 2>&1 | grep -o "200 OK");  do sleep 3; done
# Start it
echo "Starting graylog2-server..."
exec /sbin/setuser graylog2 /usr/bin/java -jar /opt/graylog2-server/graylog2-server.jar >> /var/log/graylog2-server.log