#!/bin/bash
set -e

# Create the data directory if it doesn't exist
mkdir -p /data/elasticsearch
chown -R elasticsearch:elasticsearch /data/elasticsearch
chmod -R 777 /data/elasticsearch
echo "Starting elasticsearch..."
exec /sbin/setuser elasticsearch /opt/elasticsearch/bin/elasticsearch \
    -f -Des.path.data=/data/elasticsearch -Des.cluster.name=graylog2 >> /var/log/elasticsearch.log