#!/bin/bash
set -e

# Create the log directory if it doesn't exist
mkdir -p /var/log/mongodb
chown mongodb:mongodb /var/log/mongodb

# Create the data directory if it doesn't exist
chmod 775 /data
mkdir -p /data/mongodb
chmod 775 /data/mongodb
chown mongodb:mongodb /data/mongodb

echo "Starting mongodb..."
exec /sbin/setuser mongodb /usr/bin/mongod --dbpath=/data/mongodb --smallfiles --quiet --logappend --logpath=/var/log/mongodb/mongodb.log