#!/bin/bash
set -e
# Wait for server
while ! echo exit | (curl -X GET -SsI localhost:12900/api-browser 2>&1 | grep -o "200 OK"); do sleep 3; done
# Start it
echo "Starting graylog2-web-interface..."
exec /sbin/setuser graylog2 /opt/graylog2-web-interface/bin/graylog2-web-interface >> /var/log/graylog2-web-interface.log